SEED: 9 
COLLECT_STEPS: 3000

ENV:
  SCENE_PATH: /path/to/data/
  DEFAULT_AGENT: 0
  CUDA_ID: 0

SENSOR:
  POS_HEIGHT: 0.8
  HEIGHT: 192
  WIDTH: 640
  PITCH: 0

TRAIN:
  Q_MAXLEN: 30000
  WARMUP_DATA: 6000
  FULL_DATA_LEN: 30000

AGENT:
  FORWARD_MOUNT: 0.03 
  LR_ANGLE: 2. 
  UD_ANGLE: 10
  FRAMENUM_PER_STEP: 16
  REF_FRAME_INDEX: -6 
  EXPLORE_PROB: 0.
  FRONTIER:
    PCL_HEIGHT_CLIP_HIGH: 2.0
    PCL_HEIGHT_CLIP_LOW: -2.5
    MAP_DECAY: 0.98
    MAP_LOG_OCCUPIED: 2
    MAP_LOG_FREE: 1.5
    MAP_ROUND_DIGIT: 6
    MAP_MARK_RANGE: -2
    MAP_CLEAR_RANGE: -2
    RELIABLE_TRAJ_DIST: 4
    PLANNER:
      DILATION_SIZE: 8



  
